name: "버그 제보"
description: "동작하지 않거나 기대와 다른 동작을 보고합니다."
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: "요약"
      description: "한 문장으로 문제를 요약해주세요."
      placeholder: "예) 방 목록이 로드되지 않음"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "재현 방법"
      description: "문제를 재현하는 절차를 번호로 작성해주세요."
      placeholder: |
        1. 페이지 접속
        2. '방 만들기' 클릭
        3. 오류 발생 확인
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "기대 동작"
      placeholder: "예) 방 목록이 정상적으로 표시되어야 함"

  - type: textarea
    id: actual
    attributes:
      label: "실제 동작"
      placeholder: "예) 스피너만 보이고 네트워크 에러 발생"

  - type: input
    id: env
    attributes:
      label: "환경 정보"
      description: "OS/브라우저/해상도 등"
      placeholder: "예) macOS 14 / Chrome 126 / 1440x900"

  - type: textarea
    id: logs
    attributes:
      label: "스크린샷 / 로그(선택)"
      description: "가능하면 콘솔/네트워크 로그와 스크린샷을 첨부해주세요."

  - type: checkboxes
    id: impact
    attributes:
      label: "영향도"
      options:
        - label: "회귀(이전엔 정상 동작)"
        - label: "출시 차단 이슈"

  - type: markdown
    attributes:
      value: |
        로컬에서 재현 가능하면 `pnpm dev`로 실행 후 콘솔/네트워크 로그를 함께 첨부해주세요.
